baseURL: ""
languageCode: 'en-us'
title: 'Demo for Hugo'
theme: PaperMod

params:
  homeInfoParams:
    Title: "Hello Stranger"
    Content: Welcome to my blog. Here you'll find a lot of cool information of cool stuff.
  socialIcons:
    - name: google
      url: "https://google.com/"
    - name: github
      url: "https://github.com/"
    - name: twitter
      url: "https://twitter.com/"

  cover:
    linkFullImages: true

  ShowBreadcrumbs: true

  ShowReadingTime: true

  ShowShareButtons: true

  ShowPostNavLinks: true


menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 30
      
